### ISSUE TITLE
Error at final step 3 while running portal watch command "npm run watch"

### ISSUE THREAD

**Issue by vsrp** [me-12/single-spa-portal-example#72]
I am following the instructions provided in section **"How to run this project"**. Successfully completed steps 1, 2 and first part of step 3. However, I am getting the following error while running the final part of step 3 i.e **npm run watch**. I could not figure out the issue, any help is appreciated! Thank you so much.  

Error copied from LOG file:
-------------------------------

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
**2 info using npm@5.6.0
3 info using node@v8.9.0**
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle single-spa-portal-example-frame@1.0.0~prewatch: single-spa-portal-example-frame@1.0.0
6 info lifecycle single-spa-portal-example-frame@1.0.0~watch: single-spa-portal-example-frame@1.0.0
7 verbose lifecycle single-spa-portal-example-frame@1.0.0~watch: unsafe-perm in lifecycle true
8 verbose lifecycle single-spa-portal-example-frame@1.0.0~watch: PATH: C:\Users\user1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\user1\playground\single-spa\single-spa-portal-example-master\portal\node_modules\.bin;
9 verbose lifecycle single-spa-portal-example-frame@1.0.0~watch: CWD: C:\Users\user1\playground\single-spa\single-spa-portal-example-master\portal
10 silly lifecycle single-spa-portal-example-frame@1.0.0~watch: Args: [ '/d /s /c', 'webpack-dev-server --port 9000' ]
11 silly lifecycle single-spa-portal-example-frame@1.0.0~watch: Returned: code: 1  signal: null
12 info lifecycle single-spa-portal-example-frame@1.0.0~watch: Failed to exec watch script
**13 verbose stack Error: single-spa-portal-example-frame@1.0.0 watch: `webpack-dev-server --port 9000`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\user1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\user1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)**
14 verbose pkgid single-spa-portal-example-frame@1.0.0
15 verbose cwd C:\Users\user1\playground\single-spa\single-spa-portal-example-master\portal
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
18 verbose node v8.9.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error single-spa-portal-example-frame@1.0.0 watch: `webpack-dev-server --port 9000`
22 error Exit status 1
23 error Failed at the single-spa-portal-example-frame@1.0.0 watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wenkejie** [comment]
Jump into portal ,
Then start the portal with:
npm install
npm run watch
